version: '3.8'

services:
  fastapi-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: fraud-detection-api:latest
    container_name: fraud-api
    ports:
      - "8000:8000"
    restart: always

  flask-dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    image: fraud-dashboard:latest
    container_name: fraud-dashboard
    ports:
      - "5000:5000"
    environment:
      - FASTAPI_URL=http://fastapi-backend:8000/predict
    depends_on:
      - fastapi-backend
    restart: always
