LightGBM:
  n_estimators: 1000
  learning_rate: [0.01, 0.05, 0.1]
  num_leaves: [31, 63, 127]
  max_depth: [-1, 7, 10]
  min_child_samples: [20, 50, 100]
  subsample: [0.8, 1.0]
  colsample_bytree: [0.8, 1.0]
  n_iter_search: 3